/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includeInactive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                    "text/json": components["schemas"]["RefreshTokenRequest"];
                    "application/*+json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                    "text/json": components["schemas"]["RefreshTokenRequest"];
                    "application/*+json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticatedUserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    activityDays?: number;
                    recentReconciliations?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Dev/seed-reconciliations-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SeedReconciliationsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/accounts/{accountId}/date/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconciliationDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconciliationDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    accountId?: string;
                    startDate?: string;
                    endDate?: string;
                    status?: components["schemas"]["ReconciliationStatus"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconciliationDtoPagedResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/accounts/{accountId}/date/{date}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnqueueReconciliationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/discrepancies/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    accountId?: string;
                    type?: components["schemas"]["DiscrepancyType"];
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingDiscrepancyDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/{reconciliationId}/discrepancies/{discrepancyId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reconciliationId: string;
                    discrepancyId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResolveDiscrepancyRequest"];
                    "text/json": components["schemas"]["ResolveDiscrepancyRequest"];
                    "application/*+json": components["schemas"]["ResolveDiscrepancyRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/{reconciliationId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reconciliationId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApproveReconciliationRequest"];
                    "text/json": components["schemas"]["ApproveReconciliationRequest"];
                    "application/*+json": components["schemas"]["ApproveReconciliationRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/accounts/{accountId}/date/{date}/statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatementUploadResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/{reconciliationId}/discrepancies.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reconciliationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Reconciliations/accounts/{accountId}/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconciliationRangeReport"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IngestTransactionsRequest"];
                    "text/json": components["schemas"]["IngestTransactionsRequest"];
                    "application/*+json": components["schemas"]["IngestTransactionsRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestTransactionsResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionDetailDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AccountId?: string;
                    StartDate?: string;
                    EndDate?: string;
                    Type?: string;
                    Status?: string;
                    MinAmount?: number;
                    MaxAmount?: number;
                    Category?: string;
                    SearchText?: string;
                    Page?: number;
                    PageSize?: number;
                    SortBy?: string;
                    SortDescending?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedTransactionsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/accounts/{accountId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionSummaryDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/pending-reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    accountId?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    accountId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadTransactionsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AccountId?: string;
                    StartDate?: string;
                    EndDate?: string;
                    Type?: string;
                    Status?: string;
                    MinAmount?: number;
                    MaxAmount?: number;
                    Category?: string;
                    SearchText?: string;
                    Page?: number;
                    PageSize?: number;
                    SortBy?: string;
                    SortDescending?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Transactions/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AccountId?: string;
                    StartDate?: string;
                    EndDate?: string;
                    Type?: string;
                    Status?: string;
                    MinAmount?: number;
                    MaxAmount?: number;
                    Category?: string;
                    SearchText?: string;
                    Page?: number;
                    PageSize?: number;
                    SortBy?: string;
                    SortDescending?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountListItemDto: {
            /** Format: uuid */
            id: string;
            accountNumber: string;
            accountName: string;
            type: string;
            currencyCode: string;
            /** Format: double */
            currentBalance: number;
            isActive: boolean;
            /** Format: uuid */
            institutionId: string;
        };
        ActivityPointDto: {
            /** Format: date */
            date: string;
            /** Format: int32 */
            count: number;
            /** Format: double */
            debits: number;
            /** Format: double */
            credits: number;
        };
        ApproveReconciliationRequest: {
            approvedBy: string;
            resolutionNotes?: string | null;
        };
        AuthTokenResponse: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            user?: components["schemas"]["AuthenticatedUserResponse"] | null;
        };
        AuthenticatedUserResponse: {
            id: string;
            email: string;
            displayName?: string | null;
            roles: string[];
        };
        BalanceByCurrencyDto: {
            currencyCode: string;
            /** Format: double */
            totalBalance: number;
            /** Format: int32 */
            accountCount: number;
        };
        DashboardDto: {
            balancesByCurrency: components["schemas"]["BalanceByCurrencyDto"][];
            activity: components["schemas"]["ActivityPointDto"][];
            recentReconciliations: components["schemas"]["RecentReconciliationDto"][];
            stats: components["schemas"]["DashboardQuickStatsDto"];
        };
        DashboardQuickStatsDto: {
            /** Format: int32 */
            activeAccounts: number;
            /** Format: int32 */
            transactionsToday: number;
            /** Format: int32 */
            pendingDiscrepancies: number;
            /** Format: int32 */
            reconciliationsLast7Days: number;
        };
        /** @enum {string} */
        DiscrepancyType: "MissingExternal" | "MissingInternal" | "AmountMismatch" | "DateMismatch" | "PossibleDuplicate" | "ReferenceMismatch";
        EnqueueReconciliationResponse: {
            jobId: string;
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            date: string;
        };
        IngestTransactionsRequest: {
            source: string;
            sourceType: components["schemas"]["SourceType"];
            transactions?: components["schemas"]["TransactionInput"][] | null;
            failOnFirstError: boolean;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        IngestTransactionsResult: {
            /** Format: uuid */
            batchId: string;
            /** Format: int32 */
            totalReceived: number;
            /** Format: int32 */
            processed: number;
            /** Format: int32 */
            succeeded: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            duplicates: number;
            duration: components["schemas"]["TimeSpan"];
            results: components["schemas"]["TransactionResult"][];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        PagedTransactionsDto: {
            items: components["schemas"]["TransactionListItemDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
        PendingDiscrepancyDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reconciliationId: string;
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            reconciliationDate: string;
            discrepancyType: string;
            /** Format: uuid */
            internalTransactionId?: string | null;
            externalReference?: string | null;
            /** Format: double */
            internalAmount?: number | null;
            /** Format: double */
            externalAmount?: number | null;
            /** Format: double */
            differenceAmount?: number | null;
            /** Format: date */
            internalDate?: string | null;
            /** Format: date */
            externalDate?: string | null;
            notes?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        RecentReconciliationDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            date: string;
            status: string;
            /** Format: int32 */
            discrepancyCount: number;
            /** Format: double */
            discrepancyAmount: number;
            approved: boolean;
        };
        ReconciliationDiscrepancyDto: {
            /** Format: uuid */
            id: string;
            discrepancyType: string;
            /** Format: uuid */
            internalTransactionId?: string | null;
            externalReference?: string | null;
            /** Format: double */
            internalAmount?: number | null;
            /** Format: double */
            externalAmount?: number | null;
            /** Format: double */
            differenceAmount?: number | null;
            /** Format: date */
            internalDate?: string | null;
            /** Format: date */
            externalDate?: string | null;
            isResolved: boolean;
            resolutionType?: string | null;
            resolutionNotes?: string | null;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        ReconciliationDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            reconciliationDate: string;
            status: string;
            /** Format: int32 */
            totalInternalRecords: number;
            /** Format: int32 */
            totalExternalRecords: number;
            /** Format: int32 */
            matchedCount: number;
            /** Format: int32 */
            unmatchedInternal: number;
            /** Format: int32 */
            unmatchedExternal: number;
            /** Format: double */
            totalInternalAmount: number;
            /** Format: double */
            totalExternalAmount: number;
            /** Format: double */
            discrepancyAmount: number;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: int64 */
            durationMs?: number | null;
            processedBy: string;
            approvedBy?: string | null;
            notes?: string | null;
            discrepancies: components["schemas"]["ReconciliationDiscrepancyDto"][];
        };
        ReconciliationDtoPagedResult: {
            items: components["schemas"]["ReconciliationDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasNextPage: boolean;
            readonly hasPreviousPage: boolean;
        };
        ReconciliationRangePoint: {
            /** Format: date */
            date: string;
            status: string;
            /** Format: int32 */
            matched: number;
            /** Format: int32 */
            unmatchedInternal: number;
            /** Format: int32 */
            unmatchedExternal: number;
            /** Format: double */
            discrepancyAmount: number;
            /** Format: int32 */
            discrepancyCount: number;
            approved: boolean;
        };
        ReconciliationRangeReport: {
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** Format: int32 */
            totalReconciliations: number;
            /** Format: int32 */
            completedClean: number;
            /** Format: int32 */
            completedWithDiscrepancies: number;
            /** Format: int32 */
            failed: number;
            /** Format: double */
            totalDiscrepancyAmount: number;
            /** Format: int32 */
            totalDiscrepancies: number;
            /** Format: int32 */
            totalApproved: number;
            series: components["schemas"]["ReconciliationRangePoint"][];
        };
        /** @enum {string} */
        ReconciliationStatus: "Pending" | "InProgress" | "Completed" | "CompletedWithDiscrepancies" | "Failed";
        RefreshTokenRequest: {
            refreshToken: string;
        };
        /** @enum {string} */
        ResolutionType: "Pending" | "MatchedManually" | "AdjustmentCreated" | "Ignored" | "UnderInvestigation" | "Escalated";
        ResolveDiscrepancyRequest: {
            resolution: components["schemas"]["ResolutionType"];
            resolvedBy: string;
            notes?: string | null;
        };
        SeedReconciliationsResponse: {
            runId: string;
            /** Format: int32 */
            transactionsCreated: number;
            /** Format: int32 */
            discrepanciesCreated: number;
            /** Format: int32 */
            discrepanciesResolved: number;
            /** Format: int32 */
            reconciliationsApproved: number;
            reconciliationIds: string[];
        };
        /** @enum {string} */
        SourceType: "Api" | "CsvFile" | "ExcelFile" | "Sftp" | "Manual" | "System";
        StatementUploadResponse: {
            /** Format: uuid */
            reconciliationId: string;
            /** Format: int32 */
            linesParsed: number;
            /** Format: int32 */
            matched: number;
            /** Format: int32 */
            unmatchedInternal: number;
            /** Format: int32 */
            unmatchedExternal: number;
            /** Format: double */
            discrepancyAmount: number;
            /** Format: int32 */
            discrepancyCount: number;
            status: string;
        };
        TimeSpan: {
            /** Format: int64 */
            ticks: number;
            /** Format: int32 */
            readonly days: number;
            /** Format: int32 */
            readonly hours: number;
            /** Format: int32 */
            readonly milliseconds: number;
            /** Format: int32 */
            readonly microseconds: number;
            /** Format: int32 */
            readonly nanoseconds: number;
            /** Format: int32 */
            readonly minutes: number;
            /** Format: int32 */
            readonly seconds: number;
            /** Format: double */
            readonly totalDays: number;
            /** Format: double */
            readonly totalHours: number;
            /** Format: double */
            readonly totalMilliseconds: number;
            /** Format: double */
            readonly totalMicroseconds: number;
            /** Format: double */
            readonly totalNanoseconds: number;
            /** Format: double */
            readonly totalMinutes: number;
            /** Format: double */
            readonly totalSeconds: number;
        };
        TransactionDetailDto: {
            /** Format: uuid */
            id: string;
            externalId: string;
            /** Format: uuid */
            accountId: string;
            type: string;
            status: string;
            /** Format: double */
            amount: number;
            currencyCode: string;
            /** Format: date */
            valueDate: string;
            /** Format: date */
            bookingDate: string;
            description?: string | null;
            category?: string | null;
            counterpartyName?: string | null;
            counterpartyAccount?: string | null;
            counterpartyBank?: string | null;
            /** Format: double */
            originalAmount?: number | null;
            originalCurrency?: string | null;
            /** Format: double */
            exchangeRateUsed?: number | null;
            /** Format: uuid */
            reconciliationId?: string | null;
            /** Format: date-time */
            reconciledAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            processedAt?: string | null;
        };
        TransactionInput: {
            externalId: string;
            /** Format: uuid */
            accountId: string;
            transactionType: string;
            /** Format: double */
            amount: number;
            currencyCode: string;
            /** Format: date */
            valueDate: string;
            /** Format: date */
            bookingDate?: string | null;
            description?: string | null;
            category?: string | null;
            counterpartyName?: string | null;
            counterpartyAccount?: string | null;
            counterpartyBank?: string | null;
            /** Format: double */
            originalAmount?: number | null;
            originalCurrency?: string | null;
            rawData?: {
                [key: string]: unknown;
            } | null;
        };
        TransactionListItemDto: {
            /** Format: uuid */
            id: string;
            externalId: string;
            /** Format: uuid */
            accountId: string;
            type: string;
            status: string;
            /** Format: double */
            amount: number;
            currencyCode: string;
            /** Format: date */
            valueDate: string;
            description?: string | null;
            category?: string | null;
            isReconciled: boolean;
        };
        TransactionResult: {
            externalId: string;
            /** Format: uuid */
            transactionId?: string | null;
            success: boolean;
            errorMessage?: string | null;
            isDuplicate: boolean;
        };
        TransactionSummaryDto: {
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: int32 */
            totalCount: number;
            /** Format: double */
            totalDebits: number;
            /** Format: double */
            totalCredits: number;
            /** Format: double */
            netChange: number;
            /** Format: double */
            averageTransactionAmount: number;
            /** Format: double */
            largestDebit: number;
            /** Format: double */
            largestCredit: number;
        };
        UploadRowError: {
            /** Format: int32 */
            row: number;
            error: string;
        };
        UploadTransactionsResponse: {
            fileName: string;
            /** Format: int32 */
            totalRowsParsed: number;
            ingestion?: components["schemas"]["IngestTransactionsResult"] | null;
            parseErrors: components["schemas"]["UploadRowError"][];
        };
        ValidationProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            errors: {
                [key: string]: string[];
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
